В случае Exception выкидывается не в методе close =>

1) Если при создании объекта в Try(), То и ошибка из напрмер конструктора, а та, что была в close -ее не видно
2) Если ошибка внути try(){
    }

Тода ошибка тоже игнорируется, но пишется что она была Suppressed
